name: trodrigues.net deployments
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      - name: Copy content
        uses: appleboy/scp-action@v0.1.4
        with:
          source: "_site/.*"
          target: /var/www/trodrigues.net
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY}}
          passphrase: ${{secrets.PASSPHRASE}}
          rm: true
