name: trodrigues.net deployments
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      - name: Copy content
        uses: garygrossgarten/github-action-scp@release
        with:
          local: _site
          remote: /var/www/trodrigues.net
          host: ${{ secrets.HOST }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
          rmRemote: true
